### ISSUE TITLE
Collision

### ISSUE THREAD

**Issue by Ianlaur** [algosup/2024-2025-project-2-serious-game-team-4#3]
### Description:
Collision issues when the main character collides with the NPC block it will stick to the main character.

### Commit reference:
d14bbbd5fad9f20151a22c3409082de1f3aa4289

**Comment by EmilienChinsy** [comment]
I have fixed the issue on my end but I cannot access the dev branch, So I cannot ship my fix
![image](https://github.com/user-attachments/assets/57f7ef69-4b5e-4ac2-a087-d11b80c3831e)

**Comment by Ianlaur** [comment]
Fixed!
