### ISSUE TITLE
Game settings

### ISSUE THREAD

**Issue by Ianlaur** [algosup/2024-2025-project-2-serious-game-team-4#4]
### Description:
When clicked on settings (esc button) while playing the player respawns at the begging of the scene (starting point)
### Additional notes:
Due to scene change every time the user will quit the settings page.
### Commit reference:
d14bbbd5fad9f20151a22c3409082de1f3aa4289

**Comment by EmilienChinsy** [comment]
Fixed as well but I don't have access to the github, see the setting/NPC issue for more details

**Comment by EmilienChinsy** [comment]
it's fixed
